### ISSUE TITLE
merging PRs quickly causes error

### ISSUE THREAD

**Issue by connorjclark** [patrickhulce/git3po#12]
If a config attempts to merge two PRs back to back, the second will fail. This is b/c GH has yet to have a chance to verify that the new master HEAD works with the second PR (no merge conflicts).

Should reattempt the `merge` action after a few seconds.

**Comment by paulirish** [comment]
```
❯ env GIT3PO_GH_TOKEN=<token> git3po -c lighthouse-core/scripts/git3po-rules/land-when-green.yaml --start-at=0
💎  Found #10265 (misc: delete CODEOWNERS now that we have a review rotation) at 2020-01-24T22:38:23Z, processing...
🔗  https://github.com/GoogleChrome/lighthouse/issues/10265
     Applying merge...                   ⏳
(node:9484) DeprecationWarning: label filter is deprecated, use issue filter
     Applying remove label...            ⏳
✅  Done with #10265
⤺  Issue #10257 did not match label filter, skipping
⤺  Issue #10255 did not match issue filter, skipping
⤺  Issue #10251 did not match issue filter, skipping
💎  Found #10250 (docs: add protobuf install directions) at 2020-01-22T23:51:44Z, processing...
🔗  https://github.com/GoogleChrome/lighthouse/issues/10250
     Applying merge...                   ⏳
💣  Fatal error: SuperagentPromiseError: cannot PUT https://api.github.com/repos/GoogleChrome/lighthouse/pulls/10250/merge (405)
    at /Users/paulirish/.homebrew/lib/node_modules/git3po/node_modules/superagent-bluebird-promise/index.js:89:17
    at Request.callback (/Users/paulirish/.homebrew/lib/node_modules/git3po/node_modules/superagent/lib/node/index.js:728:3)
    at /Users/paulirish/.homebrew/lib/node_modules/git3po/node_modules/superagent/lib/node/index.js:916:18
    at IncomingMessage.<anonymous> (/Users/paulirish/.homebrew/lib/node_modules/git3po/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1199:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```
